global: 
  scrape_interval: 30s

scrape_configs: 
  - job_name: "prometheus" 
    scrape_interval: 45s
    static_configs: 
    - targets: ["localhost:9090"]

  - job_name: "node-exporter" 
    static_configs: 
    - targets: ["node-exporter:9100"]

  - job_name: "cadvisor" 
    scrape_interval: 10s
    static_configs: 
    - targets: ["cadvisor:8080"]  

  # - job_name: "ubuntu-01" 
  #   scrape_interval: 10s 
  #   static_configs: 
  #   - targets: ["192.168.178.112:9100"]
  
  # Prometheus container doesn't have access to the host system, so wouldn't work now
  # - job_name: 'swarm'
  #   dockerswarm_sd_configs:
  #     - host: unix:///var/run/docker.sock
  #       role: nodes # this will discover all nodes in the cluster
  #     - host: unix:///var/run/docker.sock
  #       role: services # this will discover all services in the cluster
  #     - host: unix:///var/run/docker.sock
  #       role: tasks # this will discover all tasks (containers) in the cluster