global:
  scrape_interval: 30s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-exporter"
    file_sd_configs:
      - files:
          - "/etc/prometheus/targets.json"
        refresh_interval: 15s

  - job_name: "cadvisor"
    file_sd_configs:
      - files:
          - "/etc/prometheus/targets.json"
        refresh_interval: 15s 
  
  
  
  
  
  
  
  
  
  # - job_name: "cadvisor"
  #   docker_swarm_sd_configs:
  #     - role: tasks
  #       filters:
  #         - name: "com.docker.stack.namespace"
  #           value: "monitoring"
  #         - name: "prometheus-job"
  #           value: "cadvisor"
  #   relabel_configs:
  #     - source_labels: [__meta_docker_service_name]
  #       target_label: job
  #     - source_labels: [__meta_docker_task_port]
  #       target_label: instance

  # - job_name: "node-exporter"
  #   docker_swarm_sd_configs:
  #     - role: tasks
  #       filters:
  #         - name: "com.docker.stack.namespace"
  #           value: "monitoring"
  #         - name: "prometheus-job"
  #           value: "node-exporter"
  #   relabel_configs:
  #     - source_labels: [__meta_docker_service_name]
  #       target_label: job
  #     - source_labels: [__meta_docker_task_port]
  #       target_label: instance




  # - job_name: "cadvisor"
  #   dockerswarm_sd_configs:
  #     - host: "unix:///var/run/docker.sock"
  #       role: tasks
  #   relabel_configs:
  #     - source_labels: [__meta_dockerswarm_service_name]
  #       target_label: job
  #     - source_labels: [__address__]
  #       target_label: instance
  #     - action: keep
  #       source_labels: [__meta_dockerswarm_service_name]
  #       regex: cadvisor

  # - job_name: "node-exporter"
  #   dockerswarm_sd_configs:
  #     - host: "unix:///var/run/docker.sock"
  #       role: tasks
  #   relabel_configs:
  #       - source_labels: [__meta_dockerswarm_service_name]
  #         target_label: job
  #       - source_labels: [__address__]
  #         target_label: instance
  #       - action: keep
  #         source_labels: [__meta_dockerswarm_service_name]
  #         regex: node-exporter


  # - job_name: "cadvisor"
  #   dns_sd_configs:
  #     - names: ["tasks.monitoring_cadvisor"]
  #       type: "A"
  #       port: 8080
  #       refresh_interval: 30s
  #   relabel_configs:
  #     - source_labels: [__meta_dns_name]
  #       target_label: instance
  #     - source_labels: [__meta_dns_name]
  #       regex: 'tasks\.(.*)'
  #       target_label: job

  # - job_name: "node-exporter"
  #   dns_sd_configs:
  #     - names: ["tasks.monitoring_node-exporter"]
  #       type: "A"
  #       port: 9100
  #       refresh_interval: 30s
  #   relabel_configs:
  #     - source_labels: [__meta_dns_name]
  #       target_label: instance
  #     - source_labels: [__meta_dns_name]
  #       regex: 'tasks\.(.*)'
  #       target_label: job

  # - job_name: "node-exporter" 
  #   static_configs: 
  #   - targets: ["node-exporter:9100"]

  # - job_name: "cadvisor" 
  #   scrape_interval: 10s
  #   static_configs: 
  #   - targets: ["cadvisor:8080"]  

  # - job_name: "ubuntu-01" 
  #   scrape_interval: 10s 
  #   static_configs: 
  #   - targets: ["192.168.178.112:9100"]
  
  # Prometheus container doesn't have access to the host system, so wouldn't work now
  # - job_name: 'swarm'
  #   dockerswarm_sd_configs:
  #     - host: unix:///var/run/docker.sock
  #       role: nodes # this will discover all nodes in the cluster
  #     - host: unix:///var/run/docker.sock
  #       role: services # this will discover all services in the cluster
  #     - host: unix:///var/run/docker.sock
  #       role: tasks # this will discover all tasks (containers) in the cluster