---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-nodeport
  namespace: monitoring
spec:
  selector:
    app.kubernetes.io/instance: prom-kube-prometheus-stack-prometheus
    app.kubernetes.io/name: prometheus
  type: NodePort
  ports:
  - name: web
    port: 9090
    targetPort: web

---
apiVersion: v1
kind: Service
metadata:
  name: grafana-nodeport
  namespace: monitoring
spec:
  selector:
    app.kubernetes.io/instance: prom
    app.kubernetes.io/name: grafana
  type: NodePort
  ports:
  - name: http
    port: 3000
    targetPort: http
